apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }} 
    targetPort: {{ .Values.service.targetPort }}
<<<<<<< HEAD
=======
    nodePort: {{ .Values.service.port }}
>>>>>>> parent of 8cf085e... nodeport service
  selector:
    app: techtrends
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
