apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values-staging.yaml
    path: helm
    repoURL: git@github.com:lshrihari/ucnaa_project1.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy: {}
