apiVersion: v1
name: techtrends
description: TechTrends - Flask/Python/SQLite news sharing web application 
keywords:
- techtrends
version: 1.0.0
maintainers:
- name: Shrihari Vasudevan
  email: shrihari.vasudevan@gmail.com
